apiVersion: v2
name: cluster-api-proxmox
description: Install CAPMOX manifests to generate a fully working Kubernetes cluster
keywords:
- clusterapi
- capmox
- provisioning
- bootstrapping
- kubernetes
- proxmox
version: 1.0.5
appVersion: v1beta1
home: https://github.com/ionos-cloud/cluster-api-provider-proxmox
sources:
- https://github.com/ionos-cloud/cluster-api-provider-proxmox
maintainers:
- name: Christian Rodriguez
  email: christian.rodriguez@mikroways.net
