apiVersion: v2
name: cluster-api-vsphere
description: Install Cluster API manifests to generate a fully working Kubernetes cluster
keywords:
- clusterapi
- provisioning
- bootstrapping
- kubernetes
- vsphere
version: 1.0.0
home: https://cluster-api.sigs.k8s.io/
sources:
- https://cluster-api.sigs.k8s.io/
maintainers:
- name: Lucas Di Cunzolo
  email: lucas.dicunzolo@mikroways.net
